name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "draw/config.yaml"
      - ".github/workflows/draw.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: "config/*.keymap"
      config_path: 'draw/config.yaml'
      destination: 'both'
      west_config_path: './config/'
      output_folder: 'draw'
      fail_on_error: true